apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: aws-provider-test
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - action:
          - "secretsmanager:GetSecretValue"
          - "secretsmanager:DescribeSecret"
        effect: Allow
        resource: "arn:aws:secretsmanager:us-west-2:774538585970:secret:test-Dpn4cz"
  secretRef:
    name: aws-creds
    namespace: dev
  serviceAccountNames:
    - default